# Generated by Django 5.2.7 on 2025-10-24 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('isbn', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='O ISBN deve conter exatamente 13 dígitos numéricos.', regex='^\\d{13}$')])),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
